[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "BlexMonoNerdFontMono"
style = "Bold"

[font.italic]
family = "BlexMonoNerdFontMono"
style = "Italic"

[font.normal]
family = "BlexMonoNerdFontMono"
style = "Regular"

[terminal.shell]
args = ["-l"]
program = "fish"

[window]
opacity = 0.8

[window.padding]
x = 5
y = 5

[general]
import = ["/home/pmoieni/.cache/matugen/alacritty.toml"]

[terminal]
