[formatter.toml]
command = "taplo"
options = ["fmt"]
includes = ["*.toml"]

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.lua]
command = "stylua"
includes = ["*.lua"]

[formatter.go]
command = "gofmt"
includes = ["*.go", "go.mod"]
