[config]
reload_apps = false 
set_wallpaper = false

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty.toml'
output_path = '~/.cache/matugen/alacritty.toml'

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qtct.conf'
output_path = '~/.cache/matugen/qt5ct.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct.conf'
output_path = '~/.cache/matugen/qt6ct.conf'

[templates.gtk]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.cache/matugen/gtk.css'

[templates.hypr]
input_path = '~/.config/matugen/templates/hypr.conf'
output_path = '~/.cache/matugen/hypr.conf'
